"""empty message

Revision ID: 14fdb105081e
Revises: 
Create Date: 2023-10-24 17:06:23.930813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14fdb105081e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_srgacha_usergachalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bot_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("sr_uid", sa.String(length=64), nullable=False),
        sa.Column("gacha", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_nonebot_plugin_srgacha_usergachalog")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_srgacha_usergachalog")
    # ### end Alembic commands ###
