"""empty message

Revision ID: 45e5cb091880
Revises:
Create Date: 2023-05-15 22:21:43.621127

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "45e5cb091880"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_srpanel_userpanel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bot_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("sr_uid", sa.String(length=64), nullable=False),
        sa.Column("cid", sa.String(length=64), nullable=False),
        sa.Column("info", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_srpanel_userpanel")
    # ### end Alembic commands ###
