"""empty message

Revision ID: 32e7acac5b05
Revises: 
Create Date: 2023-05-01 20:30:25.020795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e7acac5b05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_srbind_userbind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('sr_uid', sa.String(length=64), nullable=False),
    sa.Column('mys_id', sa.String(length=64), nullable=True),
    sa.Column('cookie', sa.TEXT(), nullable=True),
    sa.Column('stoken', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_srbind_userbind')
    # ### end Alembic commands ###
