"""init database

迁移 ID: 8ab00aaa7483
父迁移:
创建时间: 2024-06-08 17:21:27.478423

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8ab00aaa7483"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("nonebot_plugin_srbind",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_srbind_userbind",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bot_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("sr_uid", sa.String(length=64), nullable=False),
        sa.Column("mys_id", sa.String(length=64), nullable=True),
        sa.Column("device_id", sa.String(length=64), nullable=True),
        sa.Column("device_fp", sa.String(length=64), nullable=True),
        sa.Column("cookie", sa.TEXT(), nullable=True),
        sa.Column("stoken", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_srbind_userbind")),
        info={"bind_key": "nonebot_plugin_srbind"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_srbind_userbind")
    # ### end Alembic commands ###
